USE [master]
GO

/****** Object:  Database [CleanicLaudromat]    Script Date: 09/10/2018 1:48:29 PM ******/
CREATE DATABASE [CleanicLaudromat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CleanicLaudromat', FILENAME = N'C:\Users\Galamiton\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\CleanicLaudromat.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CleanicLaudromat_log', FILENAME = N'C:\Users\Galamiton\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\CleanicLaudromat.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CleanicLaudromat] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CleanicLaudromat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CleanicLaudromat] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [CleanicLaudromat] SET ANSI_NULLS ON 
GO

ALTER DATABASE [CleanicLaudromat] SET ANSI_PADDING ON 
GO

ALTER DATABASE [CleanicLaudromat] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [CleanicLaudromat] SET ARITHABORT ON 
GO

ALTER DATABASE [CleanicLaudromat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CleanicLaudromat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [CleanicLaudromat] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [CleanicLaudromat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [CleanicLaudromat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CleanicLaudromat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CleanicLaudromat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET RECOVERY FULL 
GO

ALTER DATABASE [CleanicLaudromat] SET  MULTI_USER 
GO

ALTER DATABASE [CleanicLaudromat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CleanicLaudromat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CleanicLaudromat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CleanicLaudromat] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CleanicLaudromat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CleanicLaudromat] SET QUERY_STORE = OFF
GO

USE [CleanicLaudromat]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CleanicLaudromat] SET  READ_WRITE 
GO

