//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanicLaudromatAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Self_service
    {
        public int transID { get; set; }
        public string name { get; set; }
        public string contact { get; set; }
        public Nullable<int> cardNum { get; set; }
        public Nullable<int> beginningBal { get; set; }
        public Nullable<int> endingBal { get; set; }
        public Nullable<int> amountUsed { get; set; }
        public Nullable<int> sukiCardNum { get; set; }
        public string hasPromo { get; set; }
        public string enlistedItems { get; set; }
        public Nullable<int> itemsTotal { get; set; }
        public string transDate { get; set; }
        public Nullable<int> totalAmount { get; set; }
        public string remarks { get; set; }
    }
}
